services:
  web:
    image: ${DOCKER_IMAGE}:production
    ports:
      - "8083:80"
    networks:
      - ${NETWORK_NAME}
    environment:
      - NODE_ENV=production
      - DEBUG=false
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  ${NETWORK_NAME}:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: 